config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[index new create]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "users#index"
  get '/www.eample.com', to: 'users#index'
  get '/www.unsplash.com', to: 'users#index'
  get '/www.image.com', to: 'users#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_comments_counter

  def update_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_likes_counter

  def update_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_comments_counter

  private

  def update_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :update_post_likes_counter

  private

  def update_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :update_author_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_author_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :update_author_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_author_posts_counter
    author.increment!(:posts_counter)
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def initialize(attributes = nil)
    super
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/models/user.rb
# Include default devise modules. Others available are:
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def initialize(attributes = nil)
    super
    self.posts_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :photo, :bio) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :photo, :bio, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @posts = Post.find(params[:post_id])
    @user = User.find(params[:user_id])

    if @posts
      @comments = @posts.comments
      respond_to do |format|
        format.html
        format.json { render json: @comments }
      end
    else
      flash[:alert] = 'Post not found'
      redirect_to user_posts_path(@user)
    end
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    @post = Post.find(params[:post_id])

    if @comment.save
      respond_to do |format|
        format.html { redirect_to user_post_path(@post.author, @post), notice: 'Comment created' }
        format.json { render json: @comment, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new, alert: 'Comment not created!' }
        format.json { render json: @comment.errors, status: :unprocessable_entry }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.create(author: current_user, post: @post)

    if @like.persisted?
      flash[:success] = 'Liked successfully!'
      redirect_to user_post_path(current_user, @post)
    else
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.author = current_user

    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to "/users/#{current_user.id}/posts", notice: 'Post created successfully'
    else
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end

  def show
    set_post

    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    set_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/comments/new.html.erb
<section class="form-post-section">
  <h2>Add a Comment</h2>

  <%= form_with(model: @comment, url: user_post_comments_path(@post), local: true) do |form| %>

    <div class='comment-form'>
      <%= form.text_area :text, placeholder: 'Please enter your comment', class: 'comment-area' %>
      <%= form.submit 'Add Comment', class: 'comment-btn' %>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<main>
  <section class="users-container">
      <div class="user-img-container">
        <img src="<%= @user.photo %>" class="user-img">
      </div>
      <div class="user-info">
        <h2 class="user-name">
          <%= link_to @user.name %>
        </h2>
        <p class="posts-counter">
          Number of posts: <%= @user.posts_counter %>
        </p>
      </div>
  </section>
  <button class='create-post-btn'>
    <%= link_to 'Create New Post', new_user_post_path(@user) %>
  </button>
  <section class="user-details-container">
      <% if @user.recent_posts.blank? %>
      <h3>No post! Please add a post.</h3>
      <% else %>
        <% @user.posts.each do |post| %>
          <article class="posts-container">
            <h3>
              Post: #
              <%= link_to post.title, user_post_path(@user, post) %>
            </h3>
            <p>
              <%= post.text %>
            </p>
            <div class="comments-likes">
              <p>Comments: <%= post.comments_counter %></p>
              <p>Likes: <%= post.likes_counter %></p>
            </div>
          </article>
          <article class="comments-section-container">
            <% if post.recent_comments.blank? %>
              <h4>No comments! Please add a comments.</h4>
            <% else %>
              <% post.recent_comments.each do |comment| %>
                <div class="comments-section">
                  <p><%= comment.author.name %>:</p>
                  <p><%= comment.text %></p>
                </div>
              <% end %>
            <% end %>
          </article>
        <% end %>
      <% end %>
      <div>
        <a class='pagination-btn' href='#'>Pagination</a>
      </div>
  </section>
</main>

app/views/posts/new.html.erb
<section class="form-post-section">
  <h2>Create a new Post</h2>

  <%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>

    <div class='post-form'>
      <%= form.text_field :title, placeholder: 'Enter Post title', class: 'post-title' %>
      <%= form.text_area :text, placeholder: 'Enter your Post text', class: 'post-area' %>
      <%= form.submit 'Create Post', class: 'post-btn' %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<main>
  <section class="user-details-container">
      <article class="posts-container">
        <h3>
          Post: #
          <%= @post.id %> by <%= @post.author.name %>
        </h3>
        <div class="comments-likes">
          <p>Comments: <%= @post.comments_counter %></p>
          <p>Likes: <%= @post.likes_counter %></p>
        </div>
        <p>
          <%= @post.text %>
        </p>
        <section class='buttons'>
          <button class='create-comment-btn'>
            <%= link_to 'Add Comment', new_user_post_comment_path(@user, @post)%>
          </button>

          <div>
            <%= form_with model: Like, url: user_post_likes_path(@post.author, @post) do |form| %>
              <%= form.submit 'Like Post', class: 'like-btn' %>
            <% end %>
          </div>
      </section>
      </article>
      <article class="comments-section-container">
        <% if @post.recent_comments.blank? %>
          <h4>No comments! Please add a comments.</h4>
        <% else %>
          <% @post.comments.each do |comment| %>
            <div class="comments-section">
              <p><%= comment.author.name %></p>
              <p><%= comment.text %></p>
            </div>
          <% end %>
        <% end %>
      </article>
  </section>
</main>

app/views/users/index.html.erb
<main>
  <% @users.each do |user| %>
    <section class="users-container">
      <div class="user-img-container">
        <img src="<%= user.photo %>" class="user-img" atr="user photo">
      </div>
      <div class="user-info">
        <h2 class="user-name">
        <%= link_to user.name, user_path(user) %>
        </h2>
        <p class="posts-counter">
          Number of posts: <%= user.posts_counter %>
        </p>
      </div>
    </section>
  <% end %>
  <%= render partial: 'devise/shared/logout' %>
</main>

app/views/users/show.html.erb
<main>
  <section class="users-container">
      <div class="user-img-container">
        <img src="<%= @user.photo %>" class="user-img">
      </div>
      <div class="user-info">
        <h2 class="user-name">
          <%= link_to @user.name %>
        </h2>
        <p class="posts-counter">
          Number of posts: <%= @user.posts_counter %>
        </p>
      </div>
  </section>
  <section class="user-details-container">
    <div class="user-bio">
      <h3>Bio</h3>
      <p><%= @user.bio %></p>
    </div>
    <% if @user.recent_posts.blank? %>
      <h3>No post! Please add a post.</h3>
    <% else %>
      <% @user.recent_posts.each do |post| %>
        <article class="posts-container">
          <h3>
            Post: #
            <%= link_to post.title, user_post_path(@user, post) %>
          </h3>
          <p><%= post.text %></p>
          <div class="comments-likes">
            <p> Comments: <%= post.comments_counter %></p>
            <p>Likes: <%= post.likes_counter %></p>
          </div>
        </article>
      <% end %>
    <% end %>
    <div>
      <a class="more-post-btn" href="<%= user_posts_path(user_id: @user.id) %>">See all posts</a>
    </div>
      <%= render partial: 'devise/shared/logout' %>
  </section>
</main>

app/views/users/show.index.erb
<p>Shows user with id</p>